package de.uni_leipzig.imise.onto_med.phenoman_editor.field;

import care.smith.phep.phenoman.core.model.phenotype.enums.TimeEntity;
import care.smith.phep.phenoman.core.model.phenotype.top_level.TimePeriod;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.text.NumberFormat;

public class TimePeriodField extends JPanel {
  private JPanel                contentPane;
  private JFormattedTextField   formattedTextField;
  private JComboBox<TimeEntity> timeEntityComboBox;

  public TimePeriodField() {
  }

  public TimePeriod getData() {
    if (formattedTextField.getValue() == null || timeEntityComboBox.getSelectedItem() == null)
      return null;

    return new TimePeriod(
        (long) formattedTextField.getValue(), (TimeEntity) timeEntityComboBox.getSelectedItem());
  }

  public void setData(TimePeriod data) {
    formattedTextField.setValue(data != null ? data.getValue() : null);
    timeEntityComboBox.setSelectedItem(data != null ? data.getUnit() : null);
  }

  public void setVisible(boolean visible) {
    contentPane.setVisible(visible);
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    contentPane = new JPanel();
    contentPane.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
    contentPane.add(formattedTextField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    contentPane.add(timeEntityComboBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return contentPane;
  }

  private void createUIComponents() {
    formattedTextField = new JFormattedTextField(NumberFormat.getNumberInstance());
    timeEntityComboBox = new JComboBox<>(TimeEntity.values());
  }
}
